apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpinas-iso-server
  labels:
    app: alpinas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpinas
      component: iso-server
  template:
    metadata:
      labels:
        app: alpinas
        component: iso-server
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: iso-storage
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
      volumes:
      - name: iso-storage
        persistentVolumeClaim:
          claimName: alpinas-iso-pvc
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alpinas-iso-server
  labels:
    app: alpinas
spec:
  selector:
    app: alpinas
    component: iso-server
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: alpinas-iso-server
  labels:
    app: alpinas
spec:
  to:
    kind: Service
    name: alpinas-iso-server
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
