apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: alpinas
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }

        # Add CORS headers for ISO downloads
        add_header Access-Control-Allow-Origin *;
    }
