apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: alpinas
  labels:
    app: alpinas
    component: vm
spec:
  running: false
  dataVolumeTemplates:
  - metadata:
      name: alpinas-iso
    spec:
      source:
        http:
          url: "https://alpinas-iso-server-alpinas.apps.da2.epheo.eu/alpinas-20251022-113624.iso"
      storage:
        resources:
          requests:
            storage: 2Gi
        storageClassName: lvms-vg1
  - metadata:
      name: alpinas-rootdisk
    spec:
      source:
        blank: {}
      storage:
        resources:
          requests:
            storage: 5Gi
        storageClassName: lvms-vg1
  - metadata:
      name: alpinas-datadisk-1
    spec:
      source:
        blank: {}
      storage:
        resources:
          requests:
            storage: 2Gi
        storageClassName: lvms-vg1
  - metadata:
      name: alpinas-datadisk-2
    spec:
      source:
        blank: {}
      storage:
        resources:
          requests:
            storage: 2Gi
        storageClassName: lvms-vg1
  - metadata:
      name: alpinas-datadisk-3
    spec:
      source:
        blank: {}
      storage:
        resources:
          requests:
            storage: 2Gi
        storageClassName: lvms-vg1
  - metadata:
      name: alpinas-datadisk-4
    spec:
      source:
        blank: {}
      storage:
        resources:
          requests:
            storage: 2Gi
        storageClassName: lvms-vg1
  template:
    metadata:
      labels:
        kubevirt.io/domain: alpinas
        app: alpinas
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - name: iso
            cdrom:
              bus: sata
            bootOrder: 1
          - name: rootdisk
            disk:
              bus: virtio
            bootOrder: 2
          - name: datadisk-1
            disk:
              bus: virtio
          - name: datadisk-2
            disk:
              bus: virtio
          - name: datadisk-3
            disk:
              bus: virtio
          - name: datadisk-4
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 4Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: iso
        dataVolume:
          name: alpinas-iso
      - name: rootdisk
        dataVolume:
          name: alpinas-rootdisk
      - name: datadisk-1
        dataVolume:
          name: alpinas-datadisk-1
      - name: datadisk-2
        dataVolume:
          name: alpinas-datadisk-2
      - name: datadisk-3
        dataVolume:
          name: alpinas-datadisk-3
      - name: datadisk-4
        dataVolume:
          name: alpinas-datadisk-4
      - name: cloudinitdisk
        cloudInitNoCloud:
          secretRef:
            name: alpinas-cloudinit
