apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpinas

resources:
  - buildconfig.yaml

commonLabels:
  app.kubernetes.io/name: alpinas
  app.kubernetes.io/component: ci
  app.kubernetes.io/part-of: alpinas

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
